# 1. 붓꽃의 품종 분류 (Iris Variety Classification)

## 1-1. 데이터 적재

In [2]:
# scikit-learn의 datasets 모듈에 포함되어 있는 load_iris  함수를 사용해서 데이터를 적재
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [6]:
# load_iris가 반환한 iris 객체는 키와 값으로 구성
print("iris_dataset의 키:\n", iris_dataset.keys())

iris_dataset의 키:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [5]:
# DESCR 키에는 데이터셋에 대한 간략한 설명이 들어있음
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [7]:
# target_names의 값은 우리가 예측하려는 붓꽃 품종의 이름을 문자열 배열로 가지고 있음
print("타깃의 이름:", iris_dataset['target_names'])

타깃의 이름: ['setosa' 'versicolor' 'virginica']


In [9]:
# feature_names의 값은 각 특성을 설명하는 문자열 리스트
print("특성의 이름:\n", iris_dataset['feature_names'])

특성의 이름:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [11]:
# 실제 데이터는 target과 data 필드에 들어 있음. data는 꽃잎의 길이와 폭, 꽃받침의 길이와 폭을 수치 값으로 가지고 있는 NumPy배열
print("data의 타입:", type(iris_dataset['data']))

data의 타입: <class 'numpy.ndarray'>


In [12]:
# data 배열의 행은 개개의 꽃이 되며 열은 각 꽃에서 구한 네 개의 측정치
print("data의 크기:", iris_dataset['data'].shape)

data의 크기: (150, 4)


In [13]:
# 이 배열은 150개의 붓꽃 데이터를 가지고 있고, 머신러닝에서 각 아이템은 샘플이라 하고 속성은 특성이라고 부름
# 그러므로 data 배열의 크기는 샘플의 수에 특성의 수를 곱한 값이 됨
# 이는 scikit-learn의 스타일이며 항상 데이터가 이런 구조일 거라고 가정하고 있음
# 다음은 맨 처음 다섯 샘플의 특성 값
print("data의 처음 다섯 행:\n", iris_dataset['data'][:5])

data의 처음 다섯 행:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [14]:
# target 배열도 샘플 붓꽃의 품종을 담은 NumPy 배열
print("target의 타입:", type(iris_dataset['target']))

target의 타입: <class 'numpy.ndarray'>


In [15]:
print("target의 크기:", iris_dataset['target'].shape)

target의 크기: (150,)


In [16]:
# 붓꽃의 종류는 0에서 2까지의 정수로 기록되어 있음
print("타깃:\n", iris_dataset['target'])

타깃:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [17]:
print("숫자의 의미:\n", iris_dataset['target_names'])

숫자의 의미:
 ['setosa' 'versicolor' 'virginica']


## 1-2. 성과 측정 : 훈련 데이터와 테스트 데이터